### ISSUE TITLE
Snippets small bugs and Request

### ISSUE THREAD

**Issue by rludgero** [alsolovyev/Nunjucks#4]
Hi, first of all, good work. 😉 

### Small bugs

I just installed and when testing the snippets I found 2 small bugs.

1 - The **#** snippet has a conflict with the **Emmet Plugin**, when trigger tab and result in:

`<div id=""></div>`

2 - The raw closed tag endraw not get the right color like others.

![raw-tag](https://user-images.githubusercontent.com/896286/78586836-58b74c80-783c-11ea-9d7f-4afde228712f.png)

### Request / Suggestion

Create a endset snippet like that:

```nunjucks
{% set variable %}
    {# Code goes here... #}
{% endset %}
```

Thanks.

**Comment by alsolovyev** [comment]
#### Hi, thank you for your help. I greatly appreciate it!


* Emmet snippets are more important, so I decided to change the comment trigger to `co` [commit ef64621](https://github.com/alsolovyev/Nunjucks/commit/ef64621541b151dc72a9a687e761594d955e78de). By the way, sublime text has a shorthand for comment block `Ctrl + /` or `⌘ + /`

* Oh, my bad. Forgot to add some keywords [commit 9686332](https://github.com/alsolovyev/Nunjucks/commit/9686332bc1c598295ee5a97ddf1bac8a7cfa5044)

![fix_raw](https://user-images.githubusercontent.com/20425619/78596285-2ca7c580-7854-11ea-8478-a1c7bbd958d7.jpg)
* What trigger word would you like to use? "setb" is currently used, but it seems to me that this is a long trigger. Any suggestions? [commit 7ec0ef5](https://github.com/alsolovyev/Nunjucks/commit/7ec0ef593bb0deae834c2e4ce4a28f52b0d27a69)

![set_block](https://user-images.githubusercontent.com/20425619/78596302-33363d00-7854-11ea-9513-bdb37f03ee73.jpg)

What do you think about these changes? If everything is fine, then I'll draft a new release.

* [Nunjucks.sublime-package v1.1](https://github.com/alsolovyev/Nunjucks/files/4440512/Nunjucks.zip)
* extract it into your Sublime Text Packages directory
  * Windows: `%APPDATA%\Sublime Text 3\Packages`
  * OS X: `~/Library/Application\ Support/Sublime\ Text\ 3/Packages`
  * Linux: `~/.config/sublime-text-3/Packages`

**Comment by rludgero** [comment]
> Emmet snippets are more important, so I decided to change the comment trigger to co commit ef64621. By the way, sublime text has a shorthand for comment block Ctrl + / or ⌘ + /

👍 thanks.

Maybe **the comment snippet** isn't very useful,  I use the shorthand for comment too.

> Oh, my bad. Forgot to add some keywords

Dont worry 😉 

> What trigger word would you like to use? "setb" is currently used, but it seems to me that this is a long trigger. Any suggestions? 

**setb** is ok 👌 

> What do you think about these changes? If everything is fine, then I'll draft a new release.

Great job, thank you so much for fixing it so quickly.

Can I upgrade from the repository installation?

**Comment by alsolovyev** [comment]
> Can I upgrade from the repository installation?

Yes, the master branch is up to date.
All the best!
